name: Generate status page data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  generate-status-page-data:
    concurrency:
      group: generate-status-page-data
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ubuntu-latest
    name: Generate status page data
    steps:
      - name: Generate Kogito status page data
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml
          title: Kogito Pull Request Status
          subtitle: Kogito organization repositories CI Status
          base-branch-filter: main,^1\.*\.x$
          project-filter: kiegroup/kogito.*$
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate Optaplanner status page data
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml
          title: Optaplanner Pull Request Status
          subtitle: Kogito organization repositories CI Status
          base-branch-filter: main,^8\.*\.x$
          project-filter: kiegroup/opta.*$
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate Drools status page data
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml
          title: Drools Pull Request Status
          subtitle: Kogito organization repositories CI Status
          base-branch-filter: main,^8\.*\.x$
          project-filter: kiegroup/drools.*$
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"

